name: DadJokes
description: "Daily dad joke fetcher and email sender"
nodes:
  - key: fetch_joke
    name: FetchJoke
    file_name: fetch_joke.py
    starting_node: true
    schedule:
      cron: "30 15 * * *" # Every day at 3:30 PM UTC
      timezone: "UTC"
  - key: email_joke
    name: EmailJoke
    file_name: email_joke.py
    run_after:
      - fetch_joke
requirements: []
variables:
  - name: schedule
    key: schedule
    type: "schedule"
    value: "30 15 * * *"
    is_optional: False
    helper_message: "Schedule for the email joke"
